### ISSUE TITLE
런타임에서 정의 작성하기

### ISSUE THREAD

**Issue by EATSTEAK** [EATSTEAK/rusaint#13]
- JSON과 같은 형태의 정의 파일을 작성하여 런타임에서 분석, 작업 수행하기

**Comment by EATSTEAK** [comment]
런타임 정의 스키마에 대한 생각

[여기](https://github.com/EATSTEAK/rusaint/blob/5341678912ddb5db96a04efc4a02a6b3d7cc64e5/packages/rusaint/src/application/course_grades/mod.rs#L242-L250)를 런타임으로 정의한다 가정

```yaml
name: read_certificated_summary
application:
  baseUrl: https://ecc.ssu.ac.kr/sap/bc/webdynpro/SAP/
  name: ZCMB3W0017
inputs:
  - course_key
definitions:
  CLIENT_INSPECTOR_WD01:
    type: client_inspector
    id: WD01
  CLIENT_INSPECTOR_WD02:
    type: client_inspector
    id: WD02
  LOADING_PLACEHOLDER:
    type: loading_placeholder
    id: _loadingPlaceholder_
  PROGRESS_TYPE:
    type: combo_box
    id: ZCMB3W0017.ID_0001:VIW_MAIN.PROGC_VAR
  ATTM_CRD2:
    type: input_field
    id: ZCMB3W0017.ID_0001:VIW_MAIN.ATTM_CRD2
  EARN_CRD2:
    type: input_field
    id: ZCMB3W0017.ID_0001:VIW_MAIN.EARN_CRD2
  GT_GPA2:
    type: input_field
    id: ZCMB3W0017.ID_0001:VIW_MAIN.GT_GPA2
  CGPA2:
    type: input_field
    id: ZCMB3W0017.ID_0001:VIW_MAIN.CGPA2
  AVG2:
    type: input_field
    id: ZCMB3W0017.ID_0001:VIW_MAIN.AVG2
  PF_EARN_CRD1:
    type: input_field
    id: ZCMB3W0017.ID_0001:VIW_MAIN.T_PF_ERN_CRD1
steps:
    # use predefined actions
  - uses: close-popups
  - command: combobox_select_event
    with:
      definition: PROGRESS_TYPE
      key: {{ inputs.course_key }}
  - command: inputfield_value_command
    with:
      definition: ATTM_CRD2
    outputs:
      value: attempted_credits
  - command: inputfield_value_command
    with:
      definition: EARN_CRD2
    outputs:
      value: earned_credits
  - command: inputfield_value_command
    with:
      definition: GT_GPA2
    outputs:
      value: gpa
  - command: inputfield_value_command
    with:
      definition: CGPA2
    outputs:
      value: cgpa
  - command: inputfield_value_command
    with:
      definition: AVG2
    outputs:
      value: avg
  - command: inputfield_value_command
    with:
      definition: PF_EARN_CRD1
    outputs:
      value: pf_earned_credits      
```

Output:
```json
{
  "success": "true",
  "outputs": {
    "attempted_credits": "1234",
    "earned_credits": "1234",
    "gpa": "1234",
    "cgpa": "1234",
    "avg": "1234",
    "pf_earned_credits": "1234"
  }
}
